-- taxtype.sql


/* =============================================
 * CREATE TABLE public."taxtype"
 * ============================================*/
create table public."taxtype" (
	taxtype_id smallint generated by default as identity,
	constraint taxtype_pk primary key (taxtype_id)
);
comment on table public."taxtype" is '';	


-- =============================================
-- FIELD: taxtype_isdisabled boolean
-- =============================================
-- ADD taxtype_isdisabled
alter table public."taxtype" add taxtype_isdisabled boolean not null default false;
comment on column public."taxtype".taxtype_isdisabled is '';

-- MODIFY taxtype_isdisabled
alter table public."taxtype"
	alter column taxtype_isdisabled type boolean,
	ALTER COLUMN taxtype_isdisabled SET DEFAULT false,
	ALTER COLUMN taxtype_isdisabled SET NOT NULL;
comment on column public."taxtype".taxtype_isdisabled is '';


-- =============================================
-- FIELD: taxtype_name text
-- =============================================
-- ADD taxtype_name
alter table public."taxtype" add taxtype_name text  ;
comment on column public."taxtype".taxtype_name is '';

-- MODIFY taxtype_name
alter table public."taxtype"
	alter column taxtype_name type text,
	ALTER COLUMN taxtype_name DROP DEFAULT,
	ALTER COLUMN taxtype_name DROP NOT NULL;
comment on column public."taxtype".taxtype_name is '';


-- =============================================
-- FIELD: taxtype_model text
-- =============================================
-- ADD taxtype_model
alter table public."taxtype" add taxtype_model text  ;
comment on column public."taxtype".taxtype_model is '';

-- MODIFY taxtype_model
alter table public."taxtype"
	alter column taxtype_model type text,
	ALTER COLUMN taxtype_model DROP DEFAULT,
	ALTER COLUMN taxtype_model DROP NOT NULL;
comment on column public."taxtype".taxtype_model is '';


-- =============================================
-- FIELD: taxtype_value decimal(5, 2)
-- =============================================
-- ADD taxtype_value
alter table public."taxtype" add taxtype_value decimal(5, 2) not null default 0;
comment on column public."taxtype".taxtype_value is '';

-- MODIFY taxtype_value
alter table public."taxtype"
	alter column taxtype_value type decimal(5, 2),
	ALTER COLUMN taxtype_value SET DEFAULT 0,
	ALTER COLUMN taxtype_value SET NOT NULL;
comment on column public."taxtype".taxtype_value is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."taxtype" add _createby integer not null ;
comment on column public."taxtype"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."taxtype"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."taxtype"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."taxtype" add _createdate timestamp with time zone not null default now();
comment on column public."taxtype"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."taxtype"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."taxtype"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."taxtype" add _modifyby integer  ;
comment on column public."taxtype"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."taxtype"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."taxtype"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."taxtype" add _modifydate timestamp with time zone  ;
comment on column public."taxtype"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."taxtype"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."taxtype"._modifydate is 'waktu terakhir record dimodifikasi';




-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Add Foreign Key Constraint  	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."taxtype"
	drop constraint uq$public$taxtype$taxtype_name;
	

-- Add unique index 
alter table  public."taxtype"
	add constraint uq$public$taxtype$taxtype_name unique (taxtype_name); 

