-- jurnaltype.sql


/* =============================================
 * CREATE TABLE public."jurnaltype"
 * ============================================*/
create table public."jurnaltype" (
	jurnaltype_id smallint generated by default as identity,
	constraint jurnaltype_pk primary key (jurnaltype_id)
);
comment on table public."jurnaltype" is '';	


-- =============================================
-- FIELD: jurnaltype_name text
-- =============================================
-- ADD jurnaltype_name
alter table public."jurnaltype" add jurnaltype_name text  ;
comment on column public."jurnaltype".jurnaltype_name is '';

-- MODIFY jurnaltype_name
alter table public."jurnaltype"
	alter column jurnaltype_name type text,
	ALTER COLUMN jurnaltype_name DROP DEFAULT,
	ALTER COLUMN jurnaltype_name DROP NOT NULL;
comment on column public."jurnaltype".jurnaltype_name is '';


-- =============================================
-- FIELD: doc_id varchar(4)
-- =============================================
-- ADD doc_id
alter table public."jurnaltype" add doc_id varchar(4)  ;
comment on column public."jurnaltype".doc_id is '';

-- MODIFY doc_id
alter table public."jurnaltype"
	alter column doc_id type varchar(4),
	ALTER COLUMN doc_id DROP DEFAULT,
	ALTER COLUMN doc_id DROP NOT NULL;
comment on column public."jurnaltype".doc_id is '';


-- =============================================
-- FIELD: jurnaltype_isallowselect boolean
-- =============================================
-- ADD jurnaltype_isallowselect
alter table public."jurnaltype" add jurnaltype_isallowselect boolean not null default false;
comment on column public."jurnaltype".jurnaltype_isallowselect is '';

-- MODIFY jurnaltype_isallowselect
alter table public."jurnaltype"
	alter column jurnaltype_isallowselect type boolean,
	ALTER COLUMN jurnaltype_isallowselect SET DEFAULT false,
	ALTER COLUMN jurnaltype_isallowselect SET NOT NULL;
comment on column public."jurnaltype".jurnaltype_isallowselect is '';


-- =============================================
-- FIELD: jurnaltype_descr text
-- =============================================
-- ADD jurnaltype_descr
alter table public."jurnaltype" add jurnaltype_descr text  ;
comment on column public."jurnaltype".jurnaltype_descr is '';

-- MODIFY jurnaltype_descr
alter table public."jurnaltype"
	alter column jurnaltype_descr type text,
	ALTER COLUMN jurnaltype_descr DROP DEFAULT,
	ALTER COLUMN jurnaltype_descr DROP NOT NULL;
comment on column public."jurnaltype".jurnaltype_descr is '';


-- =============================================
-- FIELD: jurnalmodel_id varchar(16)
-- =============================================
-- ADD jurnalmodel_id
alter table public."jurnaltype" add jurnalmodel_id varchar(16)  ;
comment on column public."jurnaltype".jurnalmodel_id is '';

-- MODIFY jurnalmodel_id
alter table public."jurnaltype"
	alter column jurnalmodel_id type varchar(16),
	ALTER COLUMN jurnalmodel_id DROP DEFAULT,
	ALTER COLUMN jurnalmodel_id DROP NOT NULL;
comment on column public."jurnaltype".jurnalmodel_id is '';


-- =============================================
-- FIELD: jurnaltype_headcopyto varchar(1)
-- =============================================
-- ADD jurnaltype_headcopyto
alter table public."jurnaltype" add jurnaltype_headcopyto varchar(1)  ;
comment on column public."jurnaltype".jurnaltype_headcopyto is '';

-- MODIFY jurnaltype_headcopyto
alter table public."jurnaltype"
	alter column jurnaltype_headcopyto type varchar(1),
	ALTER COLUMN jurnaltype_headcopyto DROP DEFAULT,
	ALTER COLUMN jurnaltype_headcopyto DROP NOT NULL;
comment on column public."jurnaltype".jurnaltype_headcopyto is '';


-- =============================================
-- FIELD: jurnaltype_printout text
-- =============================================
-- ADD jurnaltype_printout
alter table public."jurnaltype" add jurnaltype_printout text  ;
comment on column public."jurnaltype".jurnaltype_printout is '';

-- MODIFY jurnaltype_printout
alter table public."jurnaltype"
	alter column jurnaltype_printout type text,
	ALTER COLUMN jurnaltype_printout DROP DEFAULT,
	ALTER COLUMN jurnaltype_printout DROP NOT NULL;
comment on column public."jurnaltype".jurnaltype_printout is '';


-- =============================================
-- FIELD: jurnaltype_title text
-- =============================================
-- ADD jurnaltype_title
alter table public."jurnaltype" add jurnaltype_title text  ;
comment on column public."jurnaltype".jurnaltype_title is '';

-- MODIFY jurnaltype_title
alter table public."jurnaltype"
	alter column jurnaltype_title type text,
	ALTER COLUMN jurnaltype_title DROP DEFAULT,
	ALTER COLUMN jurnaltype_title DROP NOT NULL;
comment on column public."jurnaltype".jurnaltype_title is '';


-- =============================================
-- FIELD: isheadhaspaymreq boolean
-- =============================================
-- ADD isheadhaspaymreq
alter table public."jurnaltype" add isheadhaspaymreq boolean not null default false;
comment on column public."jurnaltype".isheadhaspaymreq is '';

-- MODIFY isheadhaspaymreq
alter table public."jurnaltype"
	alter column isheadhaspaymreq type boolean,
	ALTER COLUMN isheadhaspaymreq SET DEFAULT false,
	ALTER COLUMN isheadhaspaymreq SET NOT NULL;
comment on column public."jurnaltype".isheadhaspaymreq is '';


-- =============================================
-- FIELD: isheadhaspaymtype boolean
-- =============================================
-- ADD isheadhaspaymtype
alter table public."jurnaltype" add isheadhaspaymtype boolean not null default false;
comment on column public."jurnaltype".isheadhaspaymtype is '';

-- MODIFY isheadhaspaymtype
alter table public."jurnaltype"
	alter column isheadhaspaymtype type boolean,
	ALTER COLUMN isheadhaspaymtype SET DEFAULT false,
	ALTER COLUMN isheadhaspaymtype SET NOT NULL;
comment on column public."jurnaltype".isheadhaspaymtype is '';


-- =============================================
-- FIELD: isheadhascoa boolean
-- =============================================
-- ADD isheadhascoa
alter table public."jurnaltype" add isheadhascoa boolean not null default false;
comment on column public."jurnaltype".isheadhascoa is '';

-- MODIFY isheadhascoa
alter table public."jurnaltype"
	alter column isheadhascoa type boolean,
	ALTER COLUMN isheadhascoa SET DEFAULT false,
	ALTER COLUMN isheadhascoa SET NOT NULL;
comment on column public."jurnaltype".isheadhascoa is '';


-- =============================================
-- FIELD: paymreqprocess text
-- =============================================
-- ADD paymreqprocess
alter table public."jurnaltype" add paymreqprocess text  ;
comment on column public."jurnaltype".paymreqprocess is '';

-- MODIFY paymreqprocess
alter table public."jurnaltype"
	alter column paymreqprocess type text,
	ALTER COLUMN paymreqprocess DROP DEFAULT,
	ALTER COLUMN paymreqprocess DROP NOT NULL;
comment on column public."jurnaltype".paymreqprocess is '';


-- =============================================
-- FIELD: isdetilallowgetap boolean
-- =============================================
-- ADD isdetilallowgetap
alter table public."jurnaltype" add isdetilallowgetap boolean not null default false;
comment on column public."jurnaltype".isdetilallowgetap is '';

-- MODIFY isdetilallowgetap
alter table public."jurnaltype"
	alter column isdetilallowgetap type boolean,
	ALTER COLUMN isdetilallowgetap SET DEFAULT false,
	ALTER COLUMN isdetilallowgetap SET NOT NULL;
comment on column public."jurnaltype".isdetilallowgetap is '';


-- =============================================
-- FIELD: isdetilallowgetar boolean
-- =============================================
-- ADD isdetilallowgetar
alter table public."jurnaltype" add isdetilallowgetar boolean not null default false;
comment on column public."jurnaltype".isdetilallowgetar is '';

-- MODIFY isdetilallowgetar
alter table public."jurnaltype"
	alter column isdetilallowgetar type boolean,
	ALTER COLUMN isdetilallowgetar SET DEFAULT false,
	ALTER COLUMN isdetilallowgetar SET NOT NULL;
comment on column public."jurnaltype".isdetilallowgetar is '';


-- =============================================
-- FIELD: isheadhasduedate boolean
-- =============================================
-- ADD isheadhasduedate
alter table public."jurnaltype" add isheadhasduedate boolean not null default false;
comment on column public."jurnaltype".isheadhasduedate is '';

-- MODIFY isheadhasduedate
alter table public."jurnaltype"
	alter column isheadhasduedate type boolean,
	ALTER COLUMN isheadhasduedate SET DEFAULT false,
	ALTER COLUMN isheadhasduedate SET NOT NULL;
comment on column public."jurnaltype".isheadhasduedate is '';


-- =============================================
-- FIELD: isheadallowchangeduedate boolean
-- =============================================
-- ADD isheadallowchangeduedate
alter table public."jurnaltype" add isheadallowchangeduedate boolean not null default false;
comment on column public."jurnaltype".isheadallowchangeduedate is '';

-- MODIFY isheadallowchangeduedate
alter table public."jurnaltype"
	alter column isheadallowchangeduedate type boolean,
	ALTER COLUMN isheadallowchangeduedate SET DEFAULT false,
	ALTER COLUMN isheadallowchangeduedate SET NOT NULL;
comment on column public."jurnaltype".isheadallowchangeduedate is '';


-- =============================================
-- FIELD: isheadhasvalue boolean
-- =============================================
-- ADD isheadhasvalue
alter table public."jurnaltype" add isheadhasvalue boolean not null default false;
comment on column public."jurnaltype".isheadhasvalue is '';

-- MODIFY isheadhasvalue
alter table public."jurnaltype"
	alter column isheadhasvalue type boolean,
	ALTER COLUMN isheadhasvalue SET DEFAULT false,
	ALTER COLUMN isheadhasvalue SET NOT NULL;
comment on column public."jurnaltype".isheadhasvalue is '';


-- =============================================
-- FIELD: isheadallowchangevalue boolean
-- =============================================
-- ADD isheadallowchangevalue
alter table public."jurnaltype" add isheadallowchangevalue boolean not null default false;
comment on column public."jurnaltype".isheadallowchangevalue is '';

-- MODIFY isheadallowchangevalue
alter table public."jurnaltype"
	alter column isheadallowchangevalue type boolean,
	ALTER COLUMN isheadallowchangevalue SET DEFAULT false,
	ALTER COLUMN isheadallowchangevalue SET NOT NULL;
comment on column public."jurnaltype".isheadallowchangevalue is '';


-- =============================================
-- FIELD: isheadallowselectcurr boolean
-- =============================================
-- ADD isheadallowselectcurr
alter table public."jurnaltype" add isheadallowselectcurr boolean not null default false;
comment on column public."jurnaltype".isheadallowselectcurr is '';

-- MODIFY isheadallowselectcurr
alter table public."jurnaltype"
	alter column isheadallowselectcurr type boolean,
	ALTER COLUMN isheadallowselectcurr SET DEFAULT false,
	ALTER COLUMN isheadallowselectcurr SET NOT NULL;
comment on column public."jurnaltype".isheadallowselectcurr is '';


-- =============================================
-- FIELD: isheadhaspartner boolean
-- =============================================
-- ADD isheadhaspartner
alter table public."jurnaltype" add isheadhaspartner boolean not null default false;
comment on column public."jurnaltype".isheadhaspartner is '';

-- MODIFY isheadhaspartner
alter table public."jurnaltype"
	alter column isheadhaspartner type boolean,
	ALTER COLUMN isheadhaspartner SET DEFAULT false,
	ALTER COLUMN isheadhaspartner SET NOT NULL;
comment on column public."jurnaltype".isheadhaspartner is '';


-- =============================================
-- FIELD: isheadpartnermandatory boolean
-- =============================================
-- ADD isheadpartnermandatory
alter table public."jurnaltype" add isheadpartnermandatory boolean not null default false;
comment on column public."jurnaltype".isheadpartnermandatory is '';

-- MODIFY isheadpartnermandatory
alter table public."jurnaltype"
	alter column isheadpartnermandatory type boolean,
	ALTER COLUMN isheadpartnermandatory SET DEFAULT false,
	ALTER COLUMN isheadpartnermandatory SET NOT NULL;
comment on column public."jurnaltype".isheadpartnermandatory is '';


-- =============================================
-- FIELD: isheadallowselectpartner boolean
-- =============================================
-- ADD isheadallowselectpartner
alter table public."jurnaltype" add isheadallowselectpartner boolean not null default false;
comment on column public."jurnaltype".isheadallowselectpartner is '';

-- MODIFY isheadallowselectpartner
alter table public."jurnaltype"
	alter column isheadallowselectpartner type boolean,
	ALTER COLUMN isheadallowselectpartner SET DEFAULT false,
	ALTER COLUMN isheadallowselectpartner SET NOT NULL;
comment on column public."jurnaltype".isheadallowselectpartner is '';


-- =============================================
-- FIELD: isheadhasunit boolean
-- =============================================
-- ADD isheadhasunit
alter table public."jurnaltype" add isheadhasunit boolean not null default false;
comment on column public."jurnaltype".isheadhasunit is '';

-- MODIFY isheadhasunit
alter table public."jurnaltype"
	alter column isheadhasunit type boolean,
	ALTER COLUMN isheadhasunit SET DEFAULT false,
	ALTER COLUMN isheadhasunit SET NOT NULL;
comment on column public."jurnaltype".isheadhasunit is '';


-- =============================================
-- FIELD: isheadunitmandatory boolean
-- =============================================
-- ADD isheadunitmandatory
alter table public."jurnaltype" add isheadunitmandatory boolean not null default false;
comment on column public."jurnaltype".isheadunitmandatory is '';

-- MODIFY isheadunitmandatory
alter table public."jurnaltype"
	alter column isheadunitmandatory type boolean,
	ALTER COLUMN isheadunitmandatory SET DEFAULT false,
	ALTER COLUMN isheadunitmandatory SET NOT NULL;
comment on column public."jurnaltype".isheadunitmandatory is '';


-- =============================================
-- FIELD: isheadallowselectunit boolean
-- =============================================
-- ADD isheadallowselectunit
alter table public."jurnaltype" add isheadallowselectunit boolean not null default false;
comment on column public."jurnaltype".isheadallowselectunit is '';

-- MODIFY isheadallowselectunit
alter table public."jurnaltype"
	alter column isheadallowselectunit type boolean,
	ALTER COLUMN isheadallowselectunit SET DEFAULT false,
	ALTER COLUMN isheadallowselectunit SET NOT NULL;
comment on column public."jurnaltype".isheadallowselectunit is '';


-- =============================================
-- FIELD: isheadhassite boolean
-- =============================================
-- ADD isheadhassite
alter table public."jurnaltype" add isheadhassite boolean not null default false;
comment on column public."jurnaltype".isheadhassite is '';

-- MODIFY isheadhassite
alter table public."jurnaltype"
	alter column isheadhassite type boolean,
	ALTER COLUMN isheadhassite SET DEFAULT false,
	ALTER COLUMN isheadhassite SET NOT NULL;
comment on column public."jurnaltype".isheadhassite is '';


-- =============================================
-- FIELD: isheadsitemandatory boolean
-- =============================================
-- ADD isheadsitemandatory
alter table public."jurnaltype" add isheadsitemandatory boolean not null default false;
comment on column public."jurnaltype".isheadsitemandatory is '';

-- MODIFY isheadsitemandatory
alter table public."jurnaltype"
	alter column isheadsitemandatory type boolean,
	ALTER COLUMN isheadsitemandatory SET DEFAULT false,
	ALTER COLUMN isheadsitemandatory SET NOT NULL;
comment on column public."jurnaltype".isheadsitemandatory is '';


-- =============================================
-- FIELD: isheadallowselectsite boolean
-- =============================================
-- ADD isheadallowselectsite
alter table public."jurnaltype" add isheadallowselectsite boolean not null default false;
comment on column public."jurnaltype".isheadallowselectsite is '';

-- MODIFY isheadallowselectsite
alter table public."jurnaltype"
	alter column isheadallowselectsite type boolean,
	ALTER COLUMN isheadallowselectsite SET DEFAULT false,
	ALTER COLUMN isheadallowselectsite SET NOT NULL;
comment on column public."jurnaltype".isheadallowselectsite is '';


-- =============================================
-- FIELD: isheadhasstruct boolean
-- =============================================
-- ADD isheadhasstruct
alter table public."jurnaltype" add isheadhasstruct boolean not null default false;
comment on column public."jurnaltype".isheadhasstruct is '';

-- MODIFY isheadhasstruct
alter table public."jurnaltype"
	alter column isheadhasstruct type boolean,
	ALTER COLUMN isheadhasstruct SET DEFAULT false,
	ALTER COLUMN isheadhasstruct SET NOT NULL;
comment on column public."jurnaltype".isheadhasstruct is '';


-- =============================================
-- FIELD: isheadstructmandatory boolean
-- =============================================
-- ADD isheadstructmandatory
alter table public."jurnaltype" add isheadstructmandatory boolean not null default false;
comment on column public."jurnaltype".isheadstructmandatory is '';

-- MODIFY isheadstructmandatory
alter table public."jurnaltype"
	alter column isheadstructmandatory type boolean,
	ALTER COLUMN isheadstructmandatory SET DEFAULT false,
	ALTER COLUMN isheadstructmandatory SET NOT NULL;
comment on column public."jurnaltype".isheadstructmandatory is '';


-- =============================================
-- FIELD: isheadallowselectstruct boolean
-- =============================================
-- ADD isheadallowselectstruct
alter table public."jurnaltype" add isheadallowselectstruct boolean not null default false;
comment on column public."jurnaltype".isheadallowselectstruct is '';

-- MODIFY isheadallowselectstruct
alter table public."jurnaltype"
	alter column isheadallowselectstruct type boolean,
	ALTER COLUMN isheadallowselectstruct SET DEFAULT false,
	ALTER COLUMN isheadallowselectstruct SET NOT NULL;
comment on column public."jurnaltype".isheadallowselectstruct is '';


-- =============================================
-- FIELD: isheadhasproject boolean
-- =============================================
-- ADD isheadhasproject
alter table public."jurnaltype" add isheadhasproject boolean not null default false;
comment on column public."jurnaltype".isheadhasproject is '';

-- MODIFY isheadhasproject
alter table public."jurnaltype"
	alter column isheadhasproject type boolean,
	ALTER COLUMN isheadhasproject SET DEFAULT false,
	ALTER COLUMN isheadhasproject SET NOT NULL;
comment on column public."jurnaltype".isheadhasproject is '';


-- =============================================
-- FIELD: isheadprojectmandatory boolean
-- =============================================
-- ADD isheadprojectmandatory
alter table public."jurnaltype" add isheadprojectmandatory boolean not null default false;
comment on column public."jurnaltype".isheadprojectmandatory is '';

-- MODIFY isheadprojectmandatory
alter table public."jurnaltype"
	alter column isheadprojectmandatory type boolean,
	ALTER COLUMN isheadprojectmandatory SET DEFAULT false,
	ALTER COLUMN isheadprojectmandatory SET NOT NULL;
comment on column public."jurnaltype".isheadprojectmandatory is '';


-- =============================================
-- FIELD: isheadallowselectproject boolean
-- =============================================
-- ADD isheadallowselectproject
alter table public."jurnaltype" add isheadallowselectproject boolean not null default false;
comment on column public."jurnaltype".isheadallowselectproject is '';

-- MODIFY isheadallowselectproject
alter table public."jurnaltype"
	alter column isheadallowselectproject type boolean,
	ALTER COLUMN isheadallowselectproject SET DEFAULT false,
	ALTER COLUMN isheadallowselectproject SET NOT NULL;
comment on column public."jurnaltype".isheadallowselectproject is '';


-- =============================================
-- FIELD: isdetilhaspartner boolean
-- =============================================
-- ADD isdetilhaspartner
alter table public."jurnaltype" add isdetilhaspartner boolean not null default false;
comment on column public."jurnaltype".isdetilhaspartner is '';

-- MODIFY isdetilhaspartner
alter table public."jurnaltype"
	alter column isdetilhaspartner type boolean,
	ALTER COLUMN isdetilhaspartner SET DEFAULT false,
	ALTER COLUMN isdetilhaspartner SET NOT NULL;
comment on column public."jurnaltype".isdetilhaspartner is '';


-- =============================================
-- FIELD: isdetilpartnermandatory boolean
-- =============================================
-- ADD isdetilpartnermandatory
alter table public."jurnaltype" add isdetilpartnermandatory boolean not null default false;
comment on column public."jurnaltype".isdetilpartnermandatory is '';

-- MODIFY isdetilpartnermandatory
alter table public."jurnaltype"
	alter column isdetilpartnermandatory type boolean,
	ALTER COLUMN isdetilpartnermandatory SET DEFAULT false,
	ALTER COLUMN isdetilpartnermandatory SET NOT NULL;
comment on column public."jurnaltype".isdetilpartnermandatory is '';


-- =============================================
-- FIELD: isdetilallowselectpartner boolean
-- =============================================
-- ADD isdetilallowselectpartner
alter table public."jurnaltype" add isdetilallowselectpartner boolean not null default false;
comment on column public."jurnaltype".isdetilallowselectpartner is '';

-- MODIFY isdetilallowselectpartner
alter table public."jurnaltype"
	alter column isdetilallowselectpartner type boolean,
	ALTER COLUMN isdetilallowselectpartner SET DEFAULT false,
	ALTER COLUMN isdetilallowselectpartner SET NOT NULL;
comment on column public."jurnaltype".isdetilallowselectpartner is '';


-- =============================================
-- FIELD: isdetilhasunit boolean
-- =============================================
-- ADD isdetilhasunit
alter table public."jurnaltype" add isdetilhasunit boolean not null default false;
comment on column public."jurnaltype".isdetilhasunit is '';

-- MODIFY isdetilhasunit
alter table public."jurnaltype"
	alter column isdetilhasunit type boolean,
	ALTER COLUMN isdetilhasunit SET DEFAULT false,
	ALTER COLUMN isdetilhasunit SET NOT NULL;
comment on column public."jurnaltype".isdetilhasunit is '';


-- =============================================
-- FIELD: isdetilunitmandatory boolean
-- =============================================
-- ADD isdetilunitmandatory
alter table public."jurnaltype" add isdetilunitmandatory boolean not null default false;
comment on column public."jurnaltype".isdetilunitmandatory is '';

-- MODIFY isdetilunitmandatory
alter table public."jurnaltype"
	alter column isdetilunitmandatory type boolean,
	ALTER COLUMN isdetilunitmandatory SET DEFAULT false,
	ALTER COLUMN isdetilunitmandatory SET NOT NULL;
comment on column public."jurnaltype".isdetilunitmandatory is '';


-- =============================================
-- FIELD: isdetilallowselectunit boolean
-- =============================================
-- ADD isdetilallowselectunit
alter table public."jurnaltype" add isdetilallowselectunit boolean not null default false;
comment on column public."jurnaltype".isdetilallowselectunit is '';

-- MODIFY isdetilallowselectunit
alter table public."jurnaltype"
	alter column isdetilallowselectunit type boolean,
	ALTER COLUMN isdetilallowselectunit SET DEFAULT false,
	ALTER COLUMN isdetilallowselectunit SET NOT NULL;
comment on column public."jurnaltype".isdetilallowselectunit is '';


-- =============================================
-- FIELD: isdetilhassite boolean
-- =============================================
-- ADD isdetilhassite
alter table public."jurnaltype" add isdetilhassite boolean not null default false;
comment on column public."jurnaltype".isdetilhassite is '';

-- MODIFY isdetilhassite
alter table public."jurnaltype"
	alter column isdetilhassite type boolean,
	ALTER COLUMN isdetilhassite SET DEFAULT false,
	ALTER COLUMN isdetilhassite SET NOT NULL;
comment on column public."jurnaltype".isdetilhassite is '';


-- =============================================
-- FIELD: isdetilsitemandatory boolean
-- =============================================
-- ADD isdetilsitemandatory
alter table public."jurnaltype" add isdetilsitemandatory boolean not null default false;
comment on column public."jurnaltype".isdetilsitemandatory is '';

-- MODIFY isdetilsitemandatory
alter table public."jurnaltype"
	alter column isdetilsitemandatory type boolean,
	ALTER COLUMN isdetilsitemandatory SET DEFAULT false,
	ALTER COLUMN isdetilsitemandatory SET NOT NULL;
comment on column public."jurnaltype".isdetilsitemandatory is '';


-- =============================================
-- FIELD: isdetilallowselectsite boolean
-- =============================================
-- ADD isdetilallowselectsite
alter table public."jurnaltype" add isdetilallowselectsite boolean not null default false;
comment on column public."jurnaltype".isdetilallowselectsite is '';

-- MODIFY isdetilallowselectsite
alter table public."jurnaltype"
	alter column isdetilallowselectsite type boolean,
	ALTER COLUMN isdetilallowselectsite SET DEFAULT false,
	ALTER COLUMN isdetilallowselectsite SET NOT NULL;
comment on column public."jurnaltype".isdetilallowselectsite is '';


-- =============================================
-- FIELD: isdetilhasstruct boolean
-- =============================================
-- ADD isdetilhasstruct
alter table public."jurnaltype" add isdetilhasstruct boolean not null default false;
comment on column public."jurnaltype".isdetilhasstruct is '';

-- MODIFY isdetilhasstruct
alter table public."jurnaltype"
	alter column isdetilhasstruct type boolean,
	ALTER COLUMN isdetilhasstruct SET DEFAULT false,
	ALTER COLUMN isdetilhasstruct SET NOT NULL;
comment on column public."jurnaltype".isdetilhasstruct is '';


-- =============================================
-- FIELD: isdetilstructmandatory boolean
-- =============================================
-- ADD isdetilstructmandatory
alter table public."jurnaltype" add isdetilstructmandatory boolean not null default false;
comment on column public."jurnaltype".isdetilstructmandatory is '';

-- MODIFY isdetilstructmandatory
alter table public."jurnaltype"
	alter column isdetilstructmandatory type boolean,
	ALTER COLUMN isdetilstructmandatory SET DEFAULT false,
	ALTER COLUMN isdetilstructmandatory SET NOT NULL;
comment on column public."jurnaltype".isdetilstructmandatory is '';


-- =============================================
-- FIELD: isdetilallowselectstruct boolean
-- =============================================
-- ADD isdetilallowselectstruct
alter table public."jurnaltype" add isdetilallowselectstruct boolean not null default false;
comment on column public."jurnaltype".isdetilallowselectstruct is '';

-- MODIFY isdetilallowselectstruct
alter table public."jurnaltype"
	alter column isdetilallowselectstruct type boolean,
	ALTER COLUMN isdetilallowselectstruct SET DEFAULT false,
	ALTER COLUMN isdetilallowselectstruct SET NOT NULL;
comment on column public."jurnaltype".isdetilallowselectstruct is '';


-- =============================================
-- FIELD: isdetilhasproject boolean
-- =============================================
-- ADD isdetilhasproject
alter table public."jurnaltype" add isdetilhasproject boolean not null default false;
comment on column public."jurnaltype".isdetilhasproject is '';

-- MODIFY isdetilhasproject
alter table public."jurnaltype"
	alter column isdetilhasproject type boolean,
	ALTER COLUMN isdetilhasproject SET DEFAULT false,
	ALTER COLUMN isdetilhasproject SET NOT NULL;
comment on column public."jurnaltype".isdetilhasproject is '';


-- =============================================
-- FIELD: isdetilprojectmandatory boolean
-- =============================================
-- ADD isdetilprojectmandatory
alter table public."jurnaltype" add isdetilprojectmandatory boolean not null default false;
comment on column public."jurnaltype".isdetilprojectmandatory is '';

-- MODIFY isdetilprojectmandatory
alter table public."jurnaltype"
	alter column isdetilprojectmandatory type boolean,
	ALTER COLUMN isdetilprojectmandatory SET DEFAULT false,
	ALTER COLUMN isdetilprojectmandatory SET NOT NULL;
comment on column public."jurnaltype".isdetilprojectmandatory is '';


-- =============================================
-- FIELD: isdetilallowselectproject boolean
-- =============================================
-- ADD isdetilallowselectproject
alter table public."jurnaltype" add isdetilallowselectproject boolean not null default false;
comment on column public."jurnaltype".isdetilallowselectproject is '';

-- MODIFY isdetilallowselectproject
alter table public."jurnaltype"
	alter column isdetilallowselectproject type boolean,
	ALTER COLUMN isdetilallowselectproject SET DEFAULT false,
	ALTER COLUMN isdetilallowselectproject SET NOT NULL;
comment on column public."jurnaltype".isdetilallowselectproject is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."jurnaltype" add _createby integer not null ;
comment on column public."jurnaltype"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."jurnaltype"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."jurnaltype"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."jurnaltype" add _createdate timestamp with time zone not null default now();
comment on column public."jurnaltype"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."jurnaltype"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."jurnaltype"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."jurnaltype" add _modifyby integer  ;
comment on column public."jurnaltype"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."jurnaltype"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."jurnaltype"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."jurnaltype" add _modifydate timestamp with time zone  ;
comment on column public."jurnaltype"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."jurnaltype"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."jurnaltype"._modifydate is 'waktu terakhir record dimodifikasi';




-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Drop Existing Foreign Key Constraint 
ALTER TABLE public."jurnaltype" DROP CONSTRAINT fk$public$jurnaltype$doc_id;
ALTER TABLE public."jurnaltype" DROP CONSTRAINT fk$public$jurnaltype$jurnalmodel_id;


-- Add Foreign Key Constraint  
ALTER TABLE public."jurnaltype"
	ADD CONSTRAINT fk$public$jurnaltype$doc_id
	FOREIGN KEY (doc_id)
	REFERENCES core."doc"(doc_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$jurnaltype$doc_id;
CREATE INDEX idx_fk$public$jurnaltype$doc_id ON public."jurnaltype"(doc_id);	


ALTER TABLE public."jurnaltype"
	ADD CONSTRAINT fk$public$jurnaltype$jurnalmodel_id
	FOREIGN KEY (jurnalmodel_id)
	REFERENCES public."jurnalmodel"(jurnalmodel_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$jurnaltype$jurnalmodel_id;
CREATE INDEX idx_fk$public$jurnaltype$jurnalmodel_id ON public."jurnaltype"(jurnalmodel_id);	

	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."jurnaltype"
	drop constraint uq$public$jurnaltype$jurnaltype_name;
	

-- Add unique index 
alter table  public."jurnaltype"
	add constraint uq$public$jurnaltype$jurnaltype_name unique (jurnaltype_name); 

