/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/struct.apiext.js'

const moduleName = 'struct'
const headerSectionName = 'header'
const headerTableName = 'public.struct' 
const headerPrimaryKey = 'struct_id' 
const memberTableName = 'public.structmember'  
const refTableName = 'public.structref'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await struct_init(this, body) }

	// extender call
	async execute(body) { return await struct_execute(this, body) }

	// header
	async headerList(body) { return await struct_headerList(this, body) }
	async headerOpen(body) { return await struct_headerOpen(this, body) }
	async headerUpdate(body) { return await struct_headerUpdate(this, body)}
	async headerCreate(body) { return await struct_headerCreate(this, body)}
	async headerDelete(body) { return await struct_headerDelete(this, body) }

	
	// member	
	async memberList(body) { return await struct_memberList(this, body) }
	async memberOpen(body) { return await struct_memberOpen(this, body) }
	async memberUpdate(body) { return await struct_memberUpdate(this, body)}
	async memberCreate(body) { return await struct_memberCreate(this, body) }
	async memberDelete(body) { return await struct_memberDelete(this, body) }
	async memberDeleteRows(body) { return await struct_memberDeleteRows(this, body) }
	
	// ref	
	async refList(body) { return await struct_refList(this, body) }
	async refOpen(body) { return await struct_refOpen(this, body) }
	async refUpdate(body) { return await struct_refUpdate(this, body)}
	async refCreate(body) { return await struct_refCreate(this, body) }
	async refDelete(body) { return await struct_refDelete(this, body) }
	async refDeleteRows(body) { return await struct_refDeleteRows(this, body) }
			
}	

// init module
async function struct_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {}
		}
		
		if (typeof Extender.struct_init === 'function') {
			// export async function struct_init(self, initialData) {}
			await Extender.struct_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function struct_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, struct_log) {}
		return await Extender[fnName](self, db, body, struct_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function struct_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function struct_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `struct_code ILIKE '%' || \${searchtext} || '%' OR struct_name ILIKE '%' || \${searchtext} || '%'`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: structhrk_name dari field structhrk_name pada table public.structhrk dimana (public.structhrk.structhrk_id = public.struct.structhrk_id)
			if (row.structhrk_id !== undefined) {
				const { structhrk_name } = await sqlUtil.lookupdb(db, 'public.structhrk', 'structhrk_id', row.structhrk_id)
				row.structhrk_name = structhrk_name ?? null
			}
			// lookup: auth_name dari field auth_name pada table core.auth dimana (core.auth.auth_id = public.struct.auth_id)
			if (row.auth_id !== undefined) {
				const { auth_name } = await sqlUtil.lookupdb(db, 'core.auth', 'auth_id', row.auth_id)
				row.auth_name = auth_name ?? null
			}
			// lookup: struct_parent_name dari field struct_name pada table public.struct dimana (public.struct.struct_id = public.struct.struct_parent)
			if (row.struct_parent !== undefined) {
				const { struct_name } = await sqlUtil.lookupdb(db, 'public.struct', 'struct_id', row.struct_parent)
				row.struct_parent_name = struct_name ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function struct_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { struct_id: id }
		const searchMap = { struct_id: `struct_id = \${struct_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: structhrk_name dari field structhrk_name pada table public.structhrk dimana (public.structhrk.structhrk_id = public.struct.structhrk_id)
		if (data.structhrk_id !== undefined) {
			const { structhrk_name } = await sqlUtil.lookupdb(db, 'public.structhrk', 'structhrk_id', data.structhrk_id)
			data.structhrk_name = structhrk_name ?? null
		}
		// lookup: auth_name dari field auth_name pada table core.auth dimana (core.auth.auth_id = public.struct.auth_id)
		if (data.auth_id !== undefined) {
			const { auth_name } = await sqlUtil.lookupdb(db, 'core.auth', 'auth_id', data.auth_id)
			data.auth_name = auth_name ?? null
		}
		// lookup: struct_parent_name dari field struct_name pada table public.struct dimana (public.struct.struct_id = public.struct.struct_parent)
		if (data.struct_parent !== undefined) {
			const { struct_name } = await sqlUtil.lookupdb(db, 'public.struct', 'struct_id', data.struct_parent)
			data.struct_parent_name = struct_name ?? null
		}
		 
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function struct_headerCreate(self, body) {
	const { source='struct', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'STRU' }

			
			// buat short sequencer	
			const sequencer = createSequencerLine(tx, {})

			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}

			// generate short id sesuai prefix (default: STRU) reset pertahun
			const seqdata = await sequencer.yearlyshort(args.doc_id)
			data.struct_id = seqdata.id

			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, seqdata, args)
			}

			

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			struct_log(self, body, startTime, tablename, ret.struct_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function struct_headerUpdate(self, body) {
	const { source='struct', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp


		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['struct_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			struct_log(self, body, startTime, tablename, data.struct_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function struct_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {struct_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data member
			{
				const sql = `select * from ${memberTableName} where struct_id=\${struct_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowmember of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.memberDeleting === 'function') {
						// export async function memberDeleting(self, tx, rowmember, logMetadata) {}
						await Extender.memberDeleting(self, tx, rowmember, logMetadata)
					}

					const param = {structmember_id: rowmember.structmember_id}
					const cmd = sqlUtil.createDeleteCommand(memberTableName, ['structmember_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.memberDeleted === 'function') {
						// export async function memberDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.memberDeleted(self, tx, deletedRow, logMetadata)
					}					

					struct_log(self, body, startTime, memberTableName, rowmember.structmember_id, 'DELETE', {rowdata: deletedRow})
					struct_log(self, body, startTime, headerTableName, rowmember.struct_id, 'DELETE ROW MEMBER', {structmember_id: rowmember.structmember_id, tablename: memberTableName}, `removed: ${rowmember.structmember_id}`)


				}	
			}

			// hapus data ref
			{
				const sql = `select * from ${refTableName} where struct_id=\${struct_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowref of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.refDeleting === 'function') {
						// export async function refDeleting(self, tx, rowref, logMetadata) {}
						await Extender.refDeleting(self, tx, rowref, logMetadata)
					}

					const param = {structref_id: rowref.structref_id}
					const cmd = sqlUtil.createDeleteCommand(refTableName, ['structref_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.refDeleted === 'function') {
						// export async function refDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.refDeleted(self, tx, deletedRow, logMetadata)
					}					

					struct_log(self, body, startTime, refTableName, rowref.structref_id, 'DELETE', {rowdata: deletedRow})
					struct_log(self, body, startTime, headerTableName, rowref.struct_id, 'DELETE ROW REF', {structref_id: rowref.structref_id, tablename: refTableName}, `removed: ${rowref.structref_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['struct_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			struct_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// member	

async function struct_memberList(self, body) {
	const tablename = memberTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		struct_id: `struct_id=try_cast_bigint(\${struct_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.structmember_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.memberListCriteria === 'function') {
			// export async function memberListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.memberListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: user_fullname dari field user_fullname pada table core.user dimana (core.user.user_id = public.struct.user_id)
			if (row.user_id !== undefined) {
				const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', row.user_id)
				row.user_fullname = user_fullname ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function struct_memberOpen(self, body) {
	const tablename = memberTableName

	try {
		const { id } = body 
		const criteria = { structmember_id: id }
		const searchMap = { structmember_id: `structmember_id = \${structmember_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: user_fullname dari field user_fullname pada table core.user dimana (core.user.user_id = public.struct.user_id)
		if (data.user_id !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data.user_id)
			data.user_fullname = user_fullname ?? null
		}
		  
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function memberOpen(self, db, data) {}
		if (typeof Extender.memberOpen === 'function') {
			// export async function memberOpen(self, db, data) {}
			await Extender.memberOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function struct_memberCreate(self, body) {
	const { source='struct', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = memberTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'member', 
				doc_id: 'STRU'	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.doc_id)
			data.structmember_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.memberCreating === 'function') {
				// export async function memberCreating(self, tx, data, seqdata, args) {}
				await Extender.memberCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: data.struct_id
			})


			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.memberCreated === 'function') {
				// export async function memberCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.memberCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			struct_log(self, body, startTime, tablename, ret.structmember_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function struct_memberUpdate(self, body) {
	const { source='struct', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = memberTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToUpdate = {structmember_id: data.structmember_id}
			const sql = `select * from ${memberTableName} where structmember_id=\${structmember_id}`
			const rowmember = await tx.oneOrNone(sql, dataToUpdate)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.memberUpdating === 'function') {
				// export async function memberUpdating(self, tx, data) {}
				await Extender.memberUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['structmember_id'])
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowmember.struct_id
			})

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.memberUpdated === 'function') {
				// export async function memberUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.memberUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			struct_log(self, body, startTime, tablename, data.structmember_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function struct_memberDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = memberTableName

	try {

		const data_timestamp = (new Date()).toISOString()

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {structmember_id: id}
			const sql = `select * from ${memberTableName} where structmember_id=\${structmember_id}`
			const rowmember = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.memberDeleting === 'function') {
				// export async function memberDeleting(self, tx, rowmember, logMetadata) {}
				await Extender.memberDeleting(self, tx, rowmember, logMetadata)
			}

			const param = {structmember_id: rowmember.structmember_id}
			const cmd = sqlUtil.createDeleteCommand(memberTableName, ['structmember_id'])
			const deletedRow = await cmd.execute(param)


			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowmember.struct_id
			})

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.memberDeleted === 'function') {
				// export async function memberDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.memberDeleted(self, tx, deletedRow, logMetadata)
			}					

			struct_log(self, body, startTime, memberTableName, rowmember.structmember_id, 'DELETE', {rowdata: deletedRow})
			struct_log(self, body, startTime, headerTableName, rowmember.struct_id, 'DELETE ROW MEMBER', {structmember_id: rowmember.structmember_id, tablename: memberTableName}, `removed: ${rowmember.structmember_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function struct_memberDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = memberTableName


	try {


		const data_timestamp = (new Date()).toISOString()

		let struct_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {structmember_id: id}
				const sql = `select * from ${memberTableName} where structmember_id=\${structmember_id}`
				const rowmember = await tx.oneOrNone(sql, dataToRemove)
				struct_id = rowmember.struct_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.memberDeleting === 'function') {
					// async function memberDeleting(self, tx, rowmember, logMetadata) {}
					await Extender.memberDeleting(self, tx, rowmember, logMetadata)
				}

				const param = {structmember_id: rowmember.structmember_id}
				const cmd = sqlUtil.createDeleteCommand(memberTableName, ['structmember_id'])
				const deletedRow = await cmd.execute(param)

				// update timestamp pada header
				tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
					_timestamp: data_timestamp,
					pk: rowmember.struct_id
				})
				
				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.memberDeleted === 'function') {
					// export async function memberDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.memberDeleted(self, tx, deletedRow, logMetadata)
				}					

				struct_log(self, body, startTime, memberTableName, rowmember.structmember_id, 'DELETE', {rowdata: deletedRow})
				struct_log(self, body, startTime, headerTableName, rowmember.struct_id, 'DELETE ROW MEMBER', {structmember_id: rowmember.structmember_id, tablename: memberTableName}, `removed: ${rowmember.structmember_id}`)
			}
		})
		

		const res = {
			deleted: true,
			struct_id: struct_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'memberRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function memberRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}


// ref	

async function struct_refList(self, body) {
	const tablename = refTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		struct_id: `struct_id=try_cast_bigint(\${struct_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.structref_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.refListCriteria === 'function') {
			// export async function refListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.refListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: interface_name dari field interface_name pada table core.interface dimana (core.interface.interface_id = public.struct.interface_id)
			if (row.interface_id !== undefined) {
				const { interface_name } = await sqlUtil.lookupdb(db, 'core.interface', 'interface_id', row.interface_id)
				row.interface_name = interface_name ?? null
			}
			 
			// field dengan tipedata json/jsonb	
			{
				if (row.ref_data) {
					row.ref_data = JSON.stringify(row.ref_data)
				}
			}
			
			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function struct_refOpen(self, body) {
	const tablename = refTableName

	try {
		const { id } = body 
		const criteria = { structref_id: id }
		const searchMap = { structref_id: `structref_id = \${structref_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: interface_name dari field interface_name pada table core.interface dimana (core.interface.interface_id = public.struct.interface_id)
		if (data.interface_id !== undefined) {
			const { interface_name } = await sqlUtil.lookupdb(db, 'core.interface', 'interface_id', data.interface_id)
			data.interface_name = interface_name ?? null
		}
		  
		// field dengan tipedata json/jsonb	
		{
			if (data.ref_data) {
				data.ref_data = JSON.stringify(data.ref_data)
			}
		}
		
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function refOpen(self, db, data) {}
		if (typeof Extender.refOpen === 'function') {
			// export async function refOpen(self, db, data) {}
			await Extender.refOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function struct_refCreate(self, body) {
	const { source='struct', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = refTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'ref', 
				doc_id: 'STRU'	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.doc_id)
			data.structref_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.refCreating === 'function') {
				// export async function refCreating(self, tx, data, seqdata, args) {}
				await Extender.refCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: data.struct_id
			})


			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.refCreated === 'function') {
				// export async function refCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.refCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			struct_log(self, body, startTime, tablename, ret.structref_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function struct_refUpdate(self, body) {
	const { source='struct', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = refTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToUpdate = {structref_id: data.structref_id}
			const sql = `select * from ${refTableName} where structref_id=\${structref_id}`
			const rowref = await tx.oneOrNone(sql, dataToUpdate)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.refUpdating === 'function') {
				// export async function refUpdating(self, tx, data) {}
				await Extender.refUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['structref_id'])
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowref.struct_id
			})

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.refUpdated === 'function') {
				// export async function refUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.refUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			struct_log(self, body, startTime, tablename, data.structref_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function struct_refDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = refTableName

	try {

		const data_timestamp = (new Date()).toISOString()

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {structref_id: id}
			const sql = `select * from ${refTableName} where structref_id=\${structref_id}`
			const rowref = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.refDeleting === 'function') {
				// export async function refDeleting(self, tx, rowref, logMetadata) {}
				await Extender.refDeleting(self, tx, rowref, logMetadata)
			}

			const param = {structref_id: rowref.structref_id}
			const cmd = sqlUtil.createDeleteCommand(refTableName, ['structref_id'])
			const deletedRow = await cmd.execute(param)


			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowref.struct_id
			})

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.refDeleted === 'function') {
				// export async function refDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.refDeleted(self, tx, deletedRow, logMetadata)
			}					

			struct_log(self, body, startTime, refTableName, rowref.structref_id, 'DELETE', {rowdata: deletedRow})
			struct_log(self, body, startTime, headerTableName, rowref.struct_id, 'DELETE ROW REF', {structref_id: rowref.structref_id, tablename: refTableName}, `removed: ${rowref.structref_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function struct_refDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = refTableName


	try {


		const data_timestamp = (new Date()).toISOString()

		let struct_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {structref_id: id}
				const sql = `select * from ${refTableName} where structref_id=\${structref_id}`
				const rowref = await tx.oneOrNone(sql, dataToRemove)
				struct_id = rowref.struct_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.refDeleting === 'function') {
					// async function refDeleting(self, tx, rowref, logMetadata) {}
					await Extender.refDeleting(self, tx, rowref, logMetadata)
				}

				const param = {structref_id: rowref.structref_id}
				const cmd = sqlUtil.createDeleteCommand(refTableName, ['structref_id'])
				const deletedRow = await cmd.execute(param)

				// update timestamp pada header
				tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
					_timestamp: data_timestamp,
					pk: rowref.struct_id
				})
				
				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.refDeleted === 'function') {
					// export async function refDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.refDeleted(self, tx, deletedRow, logMetadata)
				}					

				struct_log(self, body, startTime, refTableName, rowref.structref_id, 'DELETE', {rowdata: deletedRow})
				struct_log(self, body, startTime, headerTableName, rowref.struct_id, 'DELETE ROW REF', {structref_id: rowref.structref_id, tablename: refTableName}, `removed: ${rowref.structref_id}`)
			}
		})
		

		const res = {
			deleted: true,
			struct_id: struct_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'refRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function refRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	