-- item.sql


/* =============================================
 * CREATE TABLE public."item"
 * ============================================*/
create table public."item" (
	item_id int generated by default as identity,
	constraint item_pk primary key (item_id)
);
comment on table public."item" is '';	


-- =============================================
-- FIELD: item_isdisabled boolean
-- =============================================
-- ADD item_isdisabled
alter table public."item" add item_isdisabled boolean not null default false;
comment on column public."item".item_isdisabled is '';

-- MODIFY item_isdisabled
alter table public."item"
	alter column item_isdisabled type boolean,
	ALTER COLUMN item_isdisabled SET DEFAULT false,
	ALTER COLUMN item_isdisabled SET NOT NULL;
comment on column public."item".item_isdisabled is '';


-- =============================================
-- FIELD: item_name text
-- =============================================
-- ADD item_name
alter table public."item" add item_name text  ;
comment on column public."item".item_name is '';

-- MODIFY item_name
alter table public."item"
	alter column item_name type text,
	ALTER COLUMN item_name DROP DEFAULT,
	ALTER COLUMN item_name DROP NOT NULL;
comment on column public."item".item_name is '';


-- =============================================
-- FIELD: item_descr text
-- =============================================
-- ADD item_descr
alter table public."item" add item_descr text  ;
comment on column public."item".item_descr is '';

-- MODIFY item_descr
alter table public."item"
	alter column item_descr type text,
	ALTER COLUMN item_descr DROP DEFAULT,
	ALTER COLUMN item_descr DROP NOT NULL;
comment on column public."item".item_descr is '';


-- =============================================
-- FIELD: struct_id int
-- =============================================
-- ADD struct_id
alter table public."item" add struct_id int  ;
comment on column public."item".struct_id is '';

-- MODIFY struct_id
alter table public."item"
	alter column struct_id type int,
	ALTER COLUMN struct_id DROP DEFAULT,
	ALTER COLUMN struct_id DROP NOT NULL;
comment on column public."item".struct_id is '';


-- =============================================
-- FIELD: itemclass_id int
-- =============================================
-- ADD itemclass_id
alter table public."item" add itemclass_id int  ;
comment on column public."item".itemclass_id is '';

-- MODIFY itemclass_id
alter table public."item"
	alter column itemclass_id type int,
	ALTER COLUMN itemclass_id DROP DEFAULT,
	ALTER COLUMN itemclass_id DROP NOT NULL;
comment on column public."item".itemclass_id is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."item" add _createby integer not null ;
comment on column public."item"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."item"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."item"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."item" add _createdate timestamp with time zone not null default now();
comment on column public."item"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."item"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."item"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."item" add _modifyby integer  ;
comment on column public."item"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."item"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."item"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."item" add _modifydate timestamp with time zone  ;
comment on column public."item"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."item"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."item"._modifydate is 'waktu terakhir record dimodifikasi';




-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Drop Existing Foreign Key Constraint 
ALTER TABLE public."item" DROP CONSTRAINT fk$public$item$struct_id;
ALTER TABLE public."item" DROP CONSTRAINT fk$public$item$itemclass_id;


-- Add Foreign Key Constraint  
ALTER TABLE public."item"
	ADD CONSTRAINT fk$public$item$struct_id
	FOREIGN KEY (struct_id)
	REFERENCES public."struct"(struct_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$item$struct_id;
CREATE INDEX idx_fk$public$item$struct_id ON public."item"(struct_id);	


ALTER TABLE public."item"
	ADD CONSTRAINT fk$public$item$itemclass_id
	FOREIGN KEY (itemclass_id)
	REFERENCES public."itemclass"(itemclass_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$item$itemclass_id;
CREATE INDEX idx_fk$public$item$itemclass_id ON public."item"(itemclass_id);	

	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."item"
	drop constraint uq$public$item$item_name;
	

-- Add unique index 
alter table  public."item"
	add constraint uq$public$item$item_name unique (item_name); 

